In [5]:
import numpy as np



$\Large{\text{Outputting the basis components of the statevector represenation of a multi-qubit}} \newline \Large{\text{system}}$

In [6]:
qubitList = []

qub = 5

for i in range(qub):
    # initialize a qubit list with all qubits in the |0> state
    # create a density matrix for each qubit
    zero_qubit = [complex(1, 0), complex(0,0)]
    qubitList.append(zero_qubit)





group = []




for i in reversed(range(len(qubitList))):

  group.append([i, qubitList[i]])






"""
print([str(group[i][1]) + str(len(group)-1-i) for i in range(0,len(group))])
"""


group[4][1] = [complex(0, 0), complex(1, 0)]
group[3][1] = [complex(1/np.sqrt(2), 0), complex(0, -1/np.sqrt(2))]
group[2][1] = [complex(1, 0), complex(0, 0)]
group[1][1] = [complex(1/np.sqrt(2), 0), complex(1/np.sqrt(2), 0)]
group[0][1] = [complex(1, 0), complex(0, 0)]



vv = group[len(group)-1][1]

print("Qubit list == ")
print(group)

#print(vv)


def SV(group):
  sv = group[len(group)-1][1]

  for i in reversed(range(0, len(group)-1)):
    a = group[i][1]
    sv = np.kron(a,sv)

  return sv





MQ = np.array(SV(group), dtype = complex)
print(MQ)




def decomp(MQ):
  dim = len(MQ)
  d = [np.zeros(dim, dtype = complex) for i in range(dim)]

  for i in range(dim):

    if MQ[i] == complex(0,0):
      d[i][i] = 10
    else:
      d[i][i] = MQ[i]
  return d

#print(decomp(MQ))

dec = decomp(MQ)
#print("\n\n")
#print(dec[14])
dig = round(np.log2(len(dec)))


#print(len(dec))
#print(dig)
#print(bin(10)[2:])
#print(int(0b111111))


def out(dec):
  ddig = int('0b'+''.join(['1' for i in range(dig)]), base = 2)
  out = {}
  for i in range(ddig+1):
    a = bin(i)[2:]
    aa = a.zfill(len(bin(ddig))-2)
    #print(aa)
    out[aa] = ['']

  ind = list(out.keys())

  for i in range(len(ind)):
    out[ind[i]] = dec[i]




  return ddig, out

ddig, outc = out(dec)

outct = {}

print("\n multi-qubit state ==>")

ind = list(outc.keys())
for i in range(len(ind)):
  hee = 0
  if complex(10, 0) in outc[ind[i]]:
    hee = 0
  else:
    hel = outc[ind[i]]
    hee = hel[i]
  print("\n" + " |{}> ".format(ind[i]) + " ==> " + "{}".format(hee))
  outct[ind[i]] = hee



ind2 = list(outct.keys())


print(outct)
print(ind2)
print(len(ind2[0]))






















Qubit list == 
[[4, [(1+0j), 0j]], [3, [(0.7071067811865475+0j), (0.7071067811865475+0j)]], [2, [(1+0j), 0j]], [1, [(0.7071067811865475+0j), -0.7071067811865475j]], [0, [0j, (1+0j)]]]
[0. +0.j  0.5+0.j  0. +0.j  0. -0.5j 0. +0.j  0. +0.j  0. +0.j  0. +0.j
 0. +0.j  0.5+0.j  0. +0.j  0. -0.5j 0. +0.j  0. +0.j  0. +0.j  0. +0.j
 0. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j
 0. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j ]

 multi-qubit state ==>

 |00000>  ==> 0

 |00001>  ==> (0.4999999999999999+0j)

 |00010>  ==> 0

 |00011>  ==> -0.4999999999999999j

 |00100>  ==> 0

 |00101>  ==> 0

 |00110>  ==> 0

 |00111>  ==> 0

 |01000>  ==> 0

 |01001>  ==> (0.4999999999999999+0j)

 |01010>  ==> 0

 |01011>  ==> -0.4999999999999999j

 |01100>  ==> 0

 |01101>  ==> 0

 |01110>  ==> 0

 |01111>  ==> 0

 |10000>  ==> 0

 |10001>  ==> 0

 |10010>  ==> 0

 |10011>  ==> 0

 |10100>  ==> 0

 |10101>  ==> 0

 |10110>  ==> 0

 |10111>  ==> 0

 |11000>  =

$\Large{\text{Forming a matrix that represents a CNOT}} \newline \Large{\text{operation on any control and target qubit}}$

In [7]:
def CNT(cont, targ, qub):
  d = 2**qub
  CNT = np.eye(d)
  rows, columns = CNT.shape
  mapp = {}
  for i in range(1, columns+1):
    mapp[i] = [ind2[i-1]]

  col_list = []
  for i in mapp:
    c = mapp[i]

    num = qub - cont - 1
    if c[0][num] == str(1):
      col_list.append([i, mapp[i]])

  checker = [i[0] for i in col_list]
  qchecker = [[i[1][0] for i in col_list]]



  for i in col_list:

    if i[0] in checker:

      before = i[1][0]
      after = ""
      if before[qub - targ - 1] == '0':

         aft = list(before)

         aft[qub - targ - 1] = '1'
         after = "".join(aft)

      else:

        aft = list(before)
        aft[qub - targ - 1] = '0'
        after = "".join(aft)

      b_val = checker[qchecker[0].index(before)]

      a_val = checker[qchecker[0].index(after)]

      CNT[:, [b_val-1, a_val-1]] = CNT[:, [a_val-1, b_val-1]]
      checker[checker.index(b_val)] = -1
      checker[checker.index(a_val)] = -1






    else:
      pass


  return CNT








#control = qubit 4, target = qubit2
print(CNT(4, 2, qub))





[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
